spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: service-discovery
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  threads:
    virtual:
          enabled: true

management:
  endpoint: # Ứng với các endpoint nào thì sẽ có các yêu cầu, thiết lập tương ứng.
    health:
      probes:
        enabled: true
  endpoints:
    web: # HTTP protocol.
      exposure: # Cấu hình các endpoint nào sẽ được expose ra ngoài.
        include: "*" # Tất cả các endpoint sẽ được expose ra ngoài.
  health:
    # Liveness and Readiness probes configuration.
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

server:
  port: 8761


eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    peer-node-connect-timeout-ms: 2000
    peer-node-read-timeout-ms: 2000
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 900000
    enable-self-preservation: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90