// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.microservice.movie_proto;

public interface CreateMovieRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.CreateMovieRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.net.devh.boot.grpc.example.NewMovie movie = 1;</code>
   * @return Whether the movie field is set.
   */
  boolean hasMovie();
  /**
   * <code>.net.devh.boot.grpc.example.NewMovie movie = 1;</code>
   * @return The movie.
   */
  com.microservice.movie_proto.NewMovie getMovie();
  /**
   * <code>.net.devh.boot.grpc.example.NewMovie movie = 1;</code>
   */
  com.microservice.movie_proto.NewMovieOrBuilder getMovieOrBuilder();
}
