spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaivMinh/app-config
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
          username: MaivMinh
          password: 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

encrypt:
  key: $2a$12$SaK40zUz3blxDp.NoIr8yeHQWm3BWgugkTGEUQeDs0ZN4irM1onWC

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071