spring:
  application:
    name: bff
server:
  port: 8080


# Spring Actuator Configurations
management:
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        resilience4j:
          circuitbreaker:
            enabled: true
        http:
          server:
            requests:
              enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans,scheduledtasks"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    diskspace:
      enabled: true
    redis:
      enabled: true


# Eureka config.
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
      preferIpAddress: true
    fetch-registry: true

grpc:
  client:
    authService:
      address: ${GRPC_SERVER_AUTH_ADDRESS:static://localhost:9091}
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true
    movieService:
      address: ${GRPC_SERVER_MOVIE_ADDRESS:static://localhost:9092}
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true
    bookingService:
      address: ${GRPC_SERVER_BOOKING_ADDRESS:static://localhost:9093}
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true

# Current settings
springdoc:
  api-docs:
    path: /api-docs/v3/api-docs
  server-url: https://moviereservation.software
  server-urls:
    compute: true
  swagger-ui:
    path: /api-docs/swagger-ui.html
    disable-swagger-default-url: true
    url: /api-docs/v3/api-docs


# Circuit Breaker Configurations
resilience4j:
  circuitbreaker:
    instances:
      authService:
        register-health-indicator: true
        sliding-window-size: 12 # Bởi vì circuit breaker sử dụng gRPC, nên sẽ gấp đôi so với số lượng của REST thông thường.
        minimum-number-of-calls: 12
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20000
        permitted-number-of-calls-in-half-open-state: 6
        sliding-window-type: COUNT_BASED
        record-exceptions:
          - java.lang.Throwable
          - io.grpc.StatusRuntimeException
          - java.io.IOException
      movieService:
        register-health-indicator: true
        sliding-window-size: 12
        minimum-number-of-calls: 12
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20000
        permitted-number-of-calls-in-half-open-state: 6
        sliding-window-type: COUNT_BASED
        record-exceptions:
          - java.lang.Throwable
          - io.grpc.StatusRuntimeException
          - java.io.IOException
      bookingService:
        register-health-indicator: true
        sliding-window-size: 12
        minimum-number-of-calls: 12
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20000
        permitted-number-of-calls-in-half-open-state: 6
        sliding-window-type: COUNT_BASED
        record-exceptions:
          - java.lang.Throwable
          - io.grpc.StatusRuntimeException
          - java.io.IOException