// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.microservice.auth_proto;

public interface IsAdminResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.IsAdminResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isAdmin = 1;</code>
   * @return The isAdmin.
   */
  boolean getIsAdmin();
}
