// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.microservice.auth_proto;

public interface RefreshTokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.RefreshToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>int64 expiresIn = 2;</code>
   * @return The expiresIn.
   */
  long getExpiresIn();
}
