// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.microservice.movie_proto;

public interface UpdateMovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.UpdateMovie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return The name.
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();

  /**
   * <code>.google.protobuf.StringValue poster = 3;</code>
   * @return Whether the poster field is set.
   */
  boolean hasPoster();
  /**
   * <code>.google.protobuf.StringValue poster = 3;</code>
   * @return The poster.
   */
  com.google.protobuf.StringValue getPoster();
  /**
   * <code>.google.protobuf.StringValue poster = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getPosterOrBuilder();

  /**
   * <code>.google.protobuf.StringValue backdrop = 4;</code>
   * @return Whether the backdrop field is set.
   */
  boolean hasBackdrop();
  /**
   * <code>.google.protobuf.StringValue backdrop = 4;</code>
   * @return The backdrop.
   */
  com.google.protobuf.StringValue getBackdrop();
  /**
   * <code>.google.protobuf.StringValue backdrop = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getBackdropOrBuilder();

  /**
   * <code>.google.protobuf.StringValue description = 5;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>.google.protobuf.StringValue description = 5;</code>
   * @return The description.
   */
  com.google.protobuf.StringValue getDescription();
  /**
   * <code>.google.protobuf.StringValue description = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder();

  /**
   * <code>.google.protobuf.StringValue trailer = 6;</code>
   * @return Whether the trailer field is set.
   */
  boolean hasTrailer();
  /**
   * <code>.google.protobuf.StringValue trailer = 6;</code>
   * @return The trailer.
   */
  com.google.protobuf.StringValue getTrailer();
  /**
   * <code>.google.protobuf.StringValue trailer = 6;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTrailerOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value releaseDate = 7;</code>
   * @return Whether the releaseDate field is set.
   */
  boolean hasReleaseDate();
  /**
   * <code>.google.protobuf.Int64Value releaseDate = 7;</code>
   * @return The releaseDate.
   */
  com.google.protobuf.Int64Value getReleaseDate();
  /**
   * <code>.google.protobuf.Int64Value releaseDate = 7;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getReleaseDateOrBuilder();
}
