spring:
  cloud:
    gateway:
      routes:
        - id: fps
          uri: lb://fps
          predicates:
            - Path=/fps/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - PrefixPath=/api

        - id: api-documentation
          uri: lb://bff
          predicates:
            - Path=/api-docs/**,/v3/api-docs/**
            - Method=GET,POST,PUT,DELETE,PATCH


        - id: bff
          uri: lb://bff
          predicates:
            - Path=/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - PrefixPath=/api

  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}


server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
      preferIpAddress: true

grpc:
  client:
    authService:
      address: ${GRPC_SERVER_AUTH_ADDRESS:static://localhost:9091}
      negotiation-type: plaintext