spring:
  cloud:
    gateway:
      routes:
        - id: fps
          uri: lb://fps
          predicates:
            - Path=/fps/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - PrefixPath=/api

        - id: bff
          uri: lb://bff
          predicates:
            - Path=/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - PrefixPath=/api

  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      preferIpAddress: true

grpc:
  client:
    authService:
      address: ${GRPC_SERVER_AUTH_ADDRESS:static://localhost:9091}
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true