spring:
  cloud:
    gateway:
      routes:
        - id: fps
          uri: lb://fps
          predicates:
            - Path=/fps/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By,FPS Service

        - id: bff
          uri: lb://bff
          predicates:
            - Path=/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By,BFF

  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      preferIpAddress: true