// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.microservice.booking_proto;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.CreateCinemaRequest}
 */
public final class CreateCinemaRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.CreateCinemaRequest)
    CreateCinemaRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateCinemaRequest.newBuilder() to construct.
  private CreateCinemaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateCinemaRequest() {
    name_ = "";
    address_ = "";
    photos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateCinemaRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_CreateCinemaRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_CreateCinemaRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microservice.booking_proto.CreateCinemaRequest.class, com.microservice.booking_proto.CreateCinemaRequest.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 2;
  private volatile java.lang.Object address_;
  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCEID_FIELD_NUMBER = 3;
  private int provinceId_;
  /**
   * <code>int32 provinceId = 3;</code>
   * @return The provinceId.
   */
  @java.lang.Override
  public int getProvinceId() {
    return provinceId_;
  }

  public static final int PHOTOS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList photos_;
  /**
   * <code>repeated string photos = 4;</code>
   * @return A list containing the photos.
   */
  public com.google.protobuf.ProtocolStringList
      getPhotosList() {
    return photos_;
  }
  /**
   * <code>repeated string photos = 4;</code>
   * @return The count of photos.
   */
  public int getPhotosCount() {
    return photos_.size();
  }
  /**
   * <code>repeated string photos = 4;</code>
   * @param index The index of the element to return.
   * @return The photos at the given index.
   */
  public java.lang.String getPhotos(int index) {
    return photos_.get(index);
  }
  /**
   * <code>repeated string photos = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the photos at the given index.
   */
  public com.google.protobuf.ByteString
      getPhotosBytes(int index) {
    return photos_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
    }
    if (provinceId_ != 0) {
      output.writeInt32(3, provinceId_);
    }
    for (int i = 0; i < photos_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, photos_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
    }
    if (provinceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, provinceId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < photos_.size(); i++) {
        dataSize += computeStringSizeNoTag(photos_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPhotosList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microservice.booking_proto.CreateCinemaRequest)) {
      return super.equals(obj);
    }
    com.microservice.booking_proto.CreateCinemaRequest other = (com.microservice.booking_proto.CreateCinemaRequest) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getProvinceId()
        != other.getProvinceId()) return false;
    if (!getPhotosList()
        .equals(other.getPhotosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + PROVINCEID_FIELD_NUMBER;
    hash = (53 * hash) + getProvinceId();
    if (getPhotosCount() > 0) {
      hash = (37 * hash) + PHOTOS_FIELD_NUMBER;
      hash = (53 * hash) + getPhotosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.CreateCinemaRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microservice.booking_proto.CreateCinemaRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.CreateCinemaRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.CreateCinemaRequest)
      com.microservice.booking_proto.CreateCinemaRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_CreateCinemaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_CreateCinemaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.booking_proto.CreateCinemaRequest.class, com.microservice.booking_proto.CreateCinemaRequest.Builder.class);
    }

    // Construct using com.microservice.booking_proto.CreateCinemaRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      address_ = "";

      provinceId_ = 0;

      photos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_CreateCinemaRequest_descriptor;
    }

    @java.lang.Override
    public com.microservice.booking_proto.CreateCinemaRequest getDefaultInstanceForType() {
      return com.microservice.booking_proto.CreateCinemaRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.microservice.booking_proto.CreateCinemaRequest build() {
      com.microservice.booking_proto.CreateCinemaRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microservice.booking_proto.CreateCinemaRequest buildPartial() {
      com.microservice.booking_proto.CreateCinemaRequest result = new com.microservice.booking_proto.CreateCinemaRequest(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.address_ = address_;
      result.provinceId_ = provinceId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        photos_ = photos_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.photos_ = photos_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microservice.booking_proto.CreateCinemaRequest) {
        return mergeFrom((com.microservice.booking_proto.CreateCinemaRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microservice.booking_proto.CreateCinemaRequest other) {
      if (other == com.microservice.booking_proto.CreateCinemaRequest.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getProvinceId() != 0) {
        setProvinceId(other.getProvinceId());
      }
      if (!other.photos_.isEmpty()) {
        if (photos_.isEmpty()) {
          photos_ = other.photos_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePhotosIsMutable();
          photos_.addAll(other.photos_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              address_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              provinceId_ = input.readInt32();

              break;
            } // case 24
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePhotosIsMutable();
              photos_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 2;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private int provinceId_ ;
    /**
     * <code>int32 provinceId = 3;</code>
     * @return The provinceId.
     */
    @java.lang.Override
    public int getProvinceId() {
      return provinceId_;
    }
    /**
     * <code>int32 provinceId = 3;</code>
     * @param value The provinceId to set.
     * @return This builder for chaining.
     */
    public Builder setProvinceId(int value) {
      
      provinceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 provinceId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvinceId() {
      
      provinceId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList photos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePhotosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        photos_ = new com.google.protobuf.LazyStringArrayList(photos_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @return A list containing the photos.
     */
    public com.google.protobuf.ProtocolStringList
        getPhotosList() {
      return photos_.getUnmodifiableView();
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @return The count of photos.
     */
    public int getPhotosCount() {
      return photos_.size();
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @param index The index of the element to return.
     * @return The photos at the given index.
     */
    public java.lang.String getPhotos(int index) {
      return photos_.get(index);
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the photos at the given index.
     */
    public com.google.protobuf.ByteString
        getPhotosBytes(int index) {
      return photos_.getByteString(index);
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @param index The index to set the value at.
     * @param value The photos to set.
     * @return This builder for chaining.
     */
    public Builder setPhotos(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePhotosIsMutable();
      photos_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @param value The photos to add.
     * @return This builder for chaining.
     */
    public Builder addPhotos(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePhotosIsMutable();
      photos_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @param values The photos to add.
     * @return This builder for chaining.
     */
    public Builder addAllPhotos(
        java.lang.Iterable<java.lang.String> values) {
      ensurePhotosIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, photos_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhotos() {
      photos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string photos = 4;</code>
     * @param value The bytes of the photos to add.
     * @return This builder for chaining.
     */
    public Builder addPhotosBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePhotosIsMutable();
      photos_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.CreateCinemaRequest)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.CreateCinemaRequest)
  private static final com.microservice.booking_proto.CreateCinemaRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microservice.booking_proto.CreateCinemaRequest();
  }

  public static com.microservice.booking_proto.CreateCinemaRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateCinemaRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateCinemaRequest>() {
    @java.lang.Override
    public CreateCinemaRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateCinemaRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateCinemaRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microservice.booking_proto.CreateCinemaRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

