// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.microservice.booking_proto;

public interface GetMovieShowtimesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.GetMovieShowtimesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 movieId = 1;</code>
   * @return The movieId.
   */
  int getMovieId();
}
