// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.microservice.booking_proto;

public interface UpdateCinemaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.UpdateCinemaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>.net.devh.boot.grpc.example.Province province = 4;</code>
   * @return Whether the province field is set.
   */
  boolean hasProvince();
  /**
   * <code>.net.devh.boot.grpc.example.Province province = 4;</code>
   * @return The province.
   */
  com.microservice.booking_proto.Province getProvince();
  /**
   * <code>.net.devh.boot.grpc.example.Province province = 4;</code>
   */
  com.microservice.booking_proto.ProvinceOrBuilder getProvinceOrBuilder();
}
