// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.microservice.auth_proto;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.LoginSuccessInfo}
 */
public final class LoginSuccessInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.LoginSuccessInfo)
    LoginSuccessInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoginSuccessInfo.newBuilder() to construct.
  private LoginSuccessInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoginSuccessInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LoginSuccessInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microservice.auth_proto.AuthProto.internal_static_net_devh_boot_grpc_example_LoginSuccessInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microservice.auth_proto.AuthProto.internal_static_net_devh_boot_grpc_example_LoginSuccessInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microservice.auth_proto.LoginSuccessInfo.class, com.microservice.auth_proto.LoginSuccessInfo.Builder.class);
  }

  public static final int ACCESSTOKEN_FIELD_NUMBER = 1;
  private com.microservice.auth_proto.AccessToken accessToken_;
  /**
   * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
   * @return Whether the accessToken field is set.
   */
  @java.lang.Override
  public boolean hasAccessToken() {
    return accessToken_ != null;
  }
  /**
   * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
   * @return The accessToken.
   */
  @java.lang.Override
  public com.microservice.auth_proto.AccessToken getAccessToken() {
    return accessToken_ == null ? com.microservice.auth_proto.AccessToken.getDefaultInstance() : accessToken_;
  }
  /**
   * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
   */
  @java.lang.Override
  public com.microservice.auth_proto.AccessTokenOrBuilder getAccessTokenOrBuilder() {
    return getAccessToken();
  }

  public static final int REFRESHTOKEN_FIELD_NUMBER = 2;
  private com.microservice.auth_proto.RefreshToken refreshToken_;
  /**
   * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
   * @return Whether the refreshToken field is set.
   */
  @java.lang.Override
  public boolean hasRefreshToken() {
    return refreshToken_ != null;
  }
  /**
   * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
   * @return The refreshToken.
   */
  @java.lang.Override
  public com.microservice.auth_proto.RefreshToken getRefreshToken() {
    return refreshToken_ == null ? com.microservice.auth_proto.RefreshToken.getDefaultInstance() : refreshToken_;
  }
  /**
   * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
   */
  @java.lang.Override
  public com.microservice.auth_proto.RefreshTokenOrBuilder getRefreshTokenOrBuilder() {
    return getRefreshToken();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (accessToken_ != null) {
      output.writeMessage(1, getAccessToken());
    }
    if (refreshToken_ != null) {
      output.writeMessage(2, getRefreshToken());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (accessToken_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAccessToken());
    }
    if (refreshToken_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRefreshToken());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microservice.auth_proto.LoginSuccessInfo)) {
      return super.equals(obj);
    }
    com.microservice.auth_proto.LoginSuccessInfo other = (com.microservice.auth_proto.LoginSuccessInfo) obj;

    if (hasAccessToken() != other.hasAccessToken()) return false;
    if (hasAccessToken()) {
      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
    }
    if (hasRefreshToken() != other.hasRefreshToken()) return false;
    if (hasRefreshToken()) {
      if (!getRefreshToken()
          .equals(other.getRefreshToken())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAccessToken()) {
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
    }
    if (hasRefreshToken()) {
      hash = (37 * hash) + REFRESHTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRefreshToken().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.auth_proto.LoginSuccessInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microservice.auth_proto.LoginSuccessInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.LoginSuccessInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.LoginSuccessInfo)
      com.microservice.auth_proto.LoginSuccessInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.auth_proto.AuthProto.internal_static_net_devh_boot_grpc_example_LoginSuccessInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.auth_proto.AuthProto.internal_static_net_devh_boot_grpc_example_LoginSuccessInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.auth_proto.LoginSuccessInfo.class, com.microservice.auth_proto.LoginSuccessInfo.Builder.class);
    }

    // Construct using com.microservice.auth_proto.LoginSuccessInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (accessTokenBuilder_ == null) {
        accessToken_ = null;
      } else {
        accessToken_ = null;
        accessTokenBuilder_ = null;
      }
      if (refreshTokenBuilder_ == null) {
        refreshToken_ = null;
      } else {
        refreshToken_ = null;
        refreshTokenBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microservice.auth_proto.AuthProto.internal_static_net_devh_boot_grpc_example_LoginSuccessInfo_descriptor;
    }

    @java.lang.Override
    public com.microservice.auth_proto.LoginSuccessInfo getDefaultInstanceForType() {
      return com.microservice.auth_proto.LoginSuccessInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.microservice.auth_proto.LoginSuccessInfo build() {
      com.microservice.auth_proto.LoginSuccessInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microservice.auth_proto.LoginSuccessInfo buildPartial() {
      com.microservice.auth_proto.LoginSuccessInfo result = new com.microservice.auth_proto.LoginSuccessInfo(this);
      if (accessTokenBuilder_ == null) {
        result.accessToken_ = accessToken_;
      } else {
        result.accessToken_ = accessTokenBuilder_.build();
      }
      if (refreshTokenBuilder_ == null) {
        result.refreshToken_ = refreshToken_;
      } else {
        result.refreshToken_ = refreshTokenBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microservice.auth_proto.LoginSuccessInfo) {
        return mergeFrom((com.microservice.auth_proto.LoginSuccessInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microservice.auth_proto.LoginSuccessInfo other) {
      if (other == com.microservice.auth_proto.LoginSuccessInfo.getDefaultInstance()) return this;
      if (other.hasAccessToken()) {
        mergeAccessToken(other.getAccessToken());
      }
      if (other.hasRefreshToken()) {
        mergeRefreshToken(other.getRefreshToken());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getAccessTokenFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRefreshTokenFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private com.microservice.auth_proto.AccessToken accessToken_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.microservice.auth_proto.AccessToken, com.microservice.auth_proto.AccessToken.Builder, com.microservice.auth_proto.AccessTokenOrBuilder> accessTokenBuilder_;
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     * @return Whether the accessToken field is set.
     */
    public boolean hasAccessToken() {
      return accessTokenBuilder_ != null || accessToken_ != null;
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     * @return The accessToken.
     */
    public com.microservice.auth_proto.AccessToken getAccessToken() {
      if (accessTokenBuilder_ == null) {
        return accessToken_ == null ? com.microservice.auth_proto.AccessToken.getDefaultInstance() : accessToken_;
      } else {
        return accessTokenBuilder_.getMessage();
      }
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     */
    public Builder setAccessToken(com.microservice.auth_proto.AccessToken value) {
      if (accessTokenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accessToken_ = value;
        onChanged();
      } else {
        accessTokenBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     */
    public Builder setAccessToken(
        com.microservice.auth_proto.AccessToken.Builder builderForValue) {
      if (accessTokenBuilder_ == null) {
        accessToken_ = builderForValue.build();
        onChanged();
      } else {
        accessTokenBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     */
    public Builder mergeAccessToken(com.microservice.auth_proto.AccessToken value) {
      if (accessTokenBuilder_ == null) {
        if (accessToken_ != null) {
          accessToken_ =
            com.microservice.auth_proto.AccessToken.newBuilder(accessToken_).mergeFrom(value).buildPartial();
        } else {
          accessToken_ = value;
        }
        onChanged();
      } else {
        accessTokenBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     */
    public Builder clearAccessToken() {
      if (accessTokenBuilder_ == null) {
        accessToken_ = null;
        onChanged();
      } else {
        accessToken_ = null;
        accessTokenBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     */
    public com.microservice.auth_proto.AccessToken.Builder getAccessTokenBuilder() {
      
      onChanged();
      return getAccessTokenFieldBuilder().getBuilder();
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     */
    public com.microservice.auth_proto.AccessTokenOrBuilder getAccessTokenOrBuilder() {
      if (accessTokenBuilder_ != null) {
        return accessTokenBuilder_.getMessageOrBuilder();
      } else {
        return accessToken_ == null ?
            com.microservice.auth_proto.AccessToken.getDefaultInstance() : accessToken_;
      }
    }
    /**
     * <code>.net.devh.boot.grpc.example.AccessToken accessToken = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.microservice.auth_proto.AccessToken, com.microservice.auth_proto.AccessToken.Builder, com.microservice.auth_proto.AccessTokenOrBuilder> 
        getAccessTokenFieldBuilder() {
      if (accessTokenBuilder_ == null) {
        accessTokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.microservice.auth_proto.AccessToken, com.microservice.auth_proto.AccessToken.Builder, com.microservice.auth_proto.AccessTokenOrBuilder>(
                getAccessToken(),
                getParentForChildren(),
                isClean());
        accessToken_ = null;
      }
      return accessTokenBuilder_;
    }

    private com.microservice.auth_proto.RefreshToken refreshToken_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.microservice.auth_proto.RefreshToken, com.microservice.auth_proto.RefreshToken.Builder, com.microservice.auth_proto.RefreshTokenOrBuilder> refreshTokenBuilder_;
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     * @return Whether the refreshToken field is set.
     */
    public boolean hasRefreshToken() {
      return refreshTokenBuilder_ != null || refreshToken_ != null;
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     * @return The refreshToken.
     */
    public com.microservice.auth_proto.RefreshToken getRefreshToken() {
      if (refreshTokenBuilder_ == null) {
        return refreshToken_ == null ? com.microservice.auth_proto.RefreshToken.getDefaultInstance() : refreshToken_;
      } else {
        return refreshTokenBuilder_.getMessage();
      }
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     */
    public Builder setRefreshToken(com.microservice.auth_proto.RefreshToken value) {
      if (refreshTokenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        refreshToken_ = value;
        onChanged();
      } else {
        refreshTokenBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     */
    public Builder setRefreshToken(
        com.microservice.auth_proto.RefreshToken.Builder builderForValue) {
      if (refreshTokenBuilder_ == null) {
        refreshToken_ = builderForValue.build();
        onChanged();
      } else {
        refreshTokenBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     */
    public Builder mergeRefreshToken(com.microservice.auth_proto.RefreshToken value) {
      if (refreshTokenBuilder_ == null) {
        if (refreshToken_ != null) {
          refreshToken_ =
            com.microservice.auth_proto.RefreshToken.newBuilder(refreshToken_).mergeFrom(value).buildPartial();
        } else {
          refreshToken_ = value;
        }
        onChanged();
      } else {
        refreshTokenBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     */
    public Builder clearRefreshToken() {
      if (refreshTokenBuilder_ == null) {
        refreshToken_ = null;
        onChanged();
      } else {
        refreshToken_ = null;
        refreshTokenBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     */
    public com.microservice.auth_proto.RefreshToken.Builder getRefreshTokenBuilder() {
      
      onChanged();
      return getRefreshTokenFieldBuilder().getBuilder();
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     */
    public com.microservice.auth_proto.RefreshTokenOrBuilder getRefreshTokenOrBuilder() {
      if (refreshTokenBuilder_ != null) {
        return refreshTokenBuilder_.getMessageOrBuilder();
      } else {
        return refreshToken_ == null ?
            com.microservice.auth_proto.RefreshToken.getDefaultInstance() : refreshToken_;
      }
    }
    /**
     * <code>.net.devh.boot.grpc.example.RefreshToken refreshToken = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.microservice.auth_proto.RefreshToken, com.microservice.auth_proto.RefreshToken.Builder, com.microservice.auth_proto.RefreshTokenOrBuilder> 
        getRefreshTokenFieldBuilder() {
      if (refreshTokenBuilder_ == null) {
        refreshTokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.microservice.auth_proto.RefreshToken, com.microservice.auth_proto.RefreshToken.Builder, com.microservice.auth_proto.RefreshTokenOrBuilder>(
                getRefreshToken(),
                getParentForChildren(),
                isClean());
        refreshToken_ = null;
      }
      return refreshTokenBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.LoginSuccessInfo)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.LoginSuccessInfo)
  private static final com.microservice.auth_proto.LoginSuccessInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microservice.auth_proto.LoginSuccessInfo();
  }

  public static com.microservice.auth_proto.LoginSuccessInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginSuccessInfo>
      PARSER = new com.google.protobuf.AbstractParser<LoginSuccessInfo>() {
    @java.lang.Override
    public LoginSuccessInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LoginSuccessInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginSuccessInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microservice.auth_proto.LoginSuccessInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

