// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.microservice.booking_proto;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.GetMovieShowtimesResponse}
 */
public final class GetMovieShowtimesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.GetMovieShowtimesResponse)
    GetMovieShowtimesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetMovieShowtimesResponse.newBuilder() to construct.
  private GetMovieShowtimesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetMovieShowtimesResponse() {
    message_ = "";
    showtimes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetMovieShowtimesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_GetMovieShowtimesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_GetMovieShowtimesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microservice.booking_proto.GetMovieShowtimesResponse.class, com.microservice.booking_proto.GetMovieShowtimesResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHOWTIMES_FIELD_NUMBER = 3;
  private java.util.List<com.microservice.booking_proto.Showtime> showtimes_;
  /**
   * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.microservice.booking_proto.Showtime> getShowtimesList() {
    return showtimes_;
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.microservice.booking_proto.ShowtimeOrBuilder> 
      getShowtimesOrBuilderList() {
    return showtimes_;
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
   */
  @java.lang.Override
  public int getShowtimesCount() {
    return showtimes_.size();
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
   */
  @java.lang.Override
  public com.microservice.booking_proto.Showtime getShowtimes(int index) {
    return showtimes_.get(index);
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
   */
  @java.lang.Override
  public com.microservice.booking_proto.ShowtimeOrBuilder getShowtimesOrBuilder(
      int index) {
    return showtimes_.get(index);
  }

  public static final int TOTALELEMENT_FIELD_NUMBER = 4;
  private long totalElement_;
  /**
   * <code>int64 totalElement = 4;</code>
   * @return The totalElement.
   */
  @java.lang.Override
  public long getTotalElement() {
    return totalElement_;
  }

  public static final int TOTALPAGE_FIELD_NUMBER = 5;
  private long totalPage_;
  /**
   * <code>int64 totalPage = 5;</code>
   * @return The totalPage.
   */
  @java.lang.Override
  public long getTotalPage() {
    return totalPage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeInt32(1, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < showtimes_.size(); i++) {
      output.writeMessage(3, showtimes_.get(i));
    }
    if (totalElement_ != 0L) {
      output.writeInt64(4, totalElement_);
    }
    if (totalPage_ != 0L) {
      output.writeInt64(5, totalPage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < showtimes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, showtimes_.get(i));
    }
    if (totalElement_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalElement_);
    }
    if (totalPage_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, totalPage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microservice.booking_proto.GetMovieShowtimesResponse)) {
      return super.equals(obj);
    }
    com.microservice.booking_proto.GetMovieShowtimesResponse other = (com.microservice.booking_proto.GetMovieShowtimesResponse) obj;

    if (getStatus()
        != other.getStatus()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getShowtimesList()
        .equals(other.getShowtimesList())) return false;
    if (getTotalElement()
        != other.getTotalElement()) return false;
    if (getTotalPage()
        != other.getTotalPage()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getShowtimesCount() > 0) {
      hash = (37 * hash) + SHOWTIMES_FIELD_NUMBER;
      hash = (53 * hash) + getShowtimesList().hashCode();
    }
    hash = (37 * hash) + TOTALELEMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalElement());
    hash = (37 * hash) + TOTALPAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalPage());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.GetMovieShowtimesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microservice.booking_proto.GetMovieShowtimesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.GetMovieShowtimesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.GetMovieShowtimesResponse)
      com.microservice.booking_proto.GetMovieShowtimesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_GetMovieShowtimesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_GetMovieShowtimesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.booking_proto.GetMovieShowtimesResponse.class, com.microservice.booking_proto.GetMovieShowtimesResponse.Builder.class);
    }

    // Construct using com.microservice.booking_proto.GetMovieShowtimesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      message_ = "";

      if (showtimesBuilder_ == null) {
        showtimes_ = java.util.Collections.emptyList();
      } else {
        showtimes_ = null;
        showtimesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      totalElement_ = 0L;

      totalPage_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_GetMovieShowtimesResponse_descriptor;
    }

    @java.lang.Override
    public com.microservice.booking_proto.GetMovieShowtimesResponse getDefaultInstanceForType() {
      return com.microservice.booking_proto.GetMovieShowtimesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.microservice.booking_proto.GetMovieShowtimesResponse build() {
      com.microservice.booking_proto.GetMovieShowtimesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microservice.booking_proto.GetMovieShowtimesResponse buildPartial() {
      com.microservice.booking_proto.GetMovieShowtimesResponse result = new com.microservice.booking_proto.GetMovieShowtimesResponse(this);
      int from_bitField0_ = bitField0_;
      result.status_ = status_;
      result.message_ = message_;
      if (showtimesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          showtimes_ = java.util.Collections.unmodifiableList(showtimes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.showtimes_ = showtimes_;
      } else {
        result.showtimes_ = showtimesBuilder_.build();
      }
      result.totalElement_ = totalElement_;
      result.totalPage_ = totalPage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microservice.booking_proto.GetMovieShowtimesResponse) {
        return mergeFrom((com.microservice.booking_proto.GetMovieShowtimesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microservice.booking_proto.GetMovieShowtimesResponse other) {
      if (other == com.microservice.booking_proto.GetMovieShowtimesResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (showtimesBuilder_ == null) {
        if (!other.showtimes_.isEmpty()) {
          if (showtimes_.isEmpty()) {
            showtimes_ = other.showtimes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureShowtimesIsMutable();
            showtimes_.addAll(other.showtimes_);
          }
          onChanged();
        }
      } else {
        if (!other.showtimes_.isEmpty()) {
          if (showtimesBuilder_.isEmpty()) {
            showtimesBuilder_.dispose();
            showtimesBuilder_ = null;
            showtimes_ = other.showtimes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            showtimesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getShowtimesFieldBuilder() : null;
          } else {
            showtimesBuilder_.addAllMessages(other.showtimes_);
          }
        }
      }
      if (other.getTotalElement() != 0L) {
        setTotalElement(other.getTotalElement());
      }
      if (other.getTotalPage() != 0L) {
        setTotalPage(other.getTotalPage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readInt32();

              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              com.microservice.booking_proto.Showtime m =
                  input.readMessage(
                      com.microservice.booking_proto.Showtime.parser(),
                      extensionRegistry);
              if (showtimesBuilder_ == null) {
                ensureShowtimesIsMutable();
                showtimes_.add(m);
              } else {
                showtimesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              totalElement_ = input.readInt64();

              break;
            } // case 32
            case 40: {
              totalPage_ = input.readInt64();

              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ ;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.microservice.booking_proto.Showtime> showtimes_ =
      java.util.Collections.emptyList();
    private void ensureShowtimesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        showtimes_ = new java.util.ArrayList<com.microservice.booking_proto.Showtime>(showtimes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.microservice.booking_proto.Showtime, com.microservice.booking_proto.Showtime.Builder, com.microservice.booking_proto.ShowtimeOrBuilder> showtimesBuilder_;

    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public java.util.List<com.microservice.booking_proto.Showtime> getShowtimesList() {
      if (showtimesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(showtimes_);
      } else {
        return showtimesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public int getShowtimesCount() {
      if (showtimesBuilder_ == null) {
        return showtimes_.size();
      } else {
        return showtimesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public com.microservice.booking_proto.Showtime getShowtimes(int index) {
      if (showtimesBuilder_ == null) {
        return showtimes_.get(index);
      } else {
        return showtimesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder setShowtimes(
        int index, com.microservice.booking_proto.Showtime value) {
      if (showtimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShowtimesIsMutable();
        showtimes_.set(index, value);
        onChanged();
      } else {
        showtimesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder setShowtimes(
        int index, com.microservice.booking_proto.Showtime.Builder builderForValue) {
      if (showtimesBuilder_ == null) {
        ensureShowtimesIsMutable();
        showtimes_.set(index, builderForValue.build());
        onChanged();
      } else {
        showtimesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder addShowtimes(com.microservice.booking_proto.Showtime value) {
      if (showtimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShowtimesIsMutable();
        showtimes_.add(value);
        onChanged();
      } else {
        showtimesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder addShowtimes(
        int index, com.microservice.booking_proto.Showtime value) {
      if (showtimesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShowtimesIsMutable();
        showtimes_.add(index, value);
        onChanged();
      } else {
        showtimesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder addShowtimes(
        com.microservice.booking_proto.Showtime.Builder builderForValue) {
      if (showtimesBuilder_ == null) {
        ensureShowtimesIsMutable();
        showtimes_.add(builderForValue.build());
        onChanged();
      } else {
        showtimesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder addShowtimes(
        int index, com.microservice.booking_proto.Showtime.Builder builderForValue) {
      if (showtimesBuilder_ == null) {
        ensureShowtimesIsMutable();
        showtimes_.add(index, builderForValue.build());
        onChanged();
      } else {
        showtimesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder addAllShowtimes(
        java.lang.Iterable<? extends com.microservice.booking_proto.Showtime> values) {
      if (showtimesBuilder_ == null) {
        ensureShowtimesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, showtimes_);
        onChanged();
      } else {
        showtimesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder clearShowtimes() {
      if (showtimesBuilder_ == null) {
        showtimes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        showtimesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public Builder removeShowtimes(int index) {
      if (showtimesBuilder_ == null) {
        ensureShowtimesIsMutable();
        showtimes_.remove(index);
        onChanged();
      } else {
        showtimesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public com.microservice.booking_proto.Showtime.Builder getShowtimesBuilder(
        int index) {
      return getShowtimesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public com.microservice.booking_proto.ShowtimeOrBuilder getShowtimesOrBuilder(
        int index) {
      if (showtimesBuilder_ == null) {
        return showtimes_.get(index);  } else {
        return showtimesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public java.util.List<? extends com.microservice.booking_proto.ShowtimeOrBuilder> 
         getShowtimesOrBuilderList() {
      if (showtimesBuilder_ != null) {
        return showtimesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(showtimes_);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public com.microservice.booking_proto.Showtime.Builder addShowtimesBuilder() {
      return getShowtimesFieldBuilder().addBuilder(
          com.microservice.booking_proto.Showtime.getDefaultInstance());
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public com.microservice.booking_proto.Showtime.Builder addShowtimesBuilder(
        int index) {
      return getShowtimesFieldBuilder().addBuilder(
          index, com.microservice.booking_proto.Showtime.getDefaultInstance());
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.Showtime showtimes = 3;</code>
     */
    public java.util.List<com.microservice.booking_proto.Showtime.Builder> 
         getShowtimesBuilderList() {
      return getShowtimesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.microservice.booking_proto.Showtime, com.microservice.booking_proto.Showtime.Builder, com.microservice.booking_proto.ShowtimeOrBuilder> 
        getShowtimesFieldBuilder() {
      if (showtimesBuilder_ == null) {
        showtimesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.microservice.booking_proto.Showtime, com.microservice.booking_proto.Showtime.Builder, com.microservice.booking_proto.ShowtimeOrBuilder>(
                showtimes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        showtimes_ = null;
      }
      return showtimesBuilder_;
    }

    private long totalElement_ ;
    /**
     * <code>int64 totalElement = 4;</code>
     * @return The totalElement.
     */
    @java.lang.Override
    public long getTotalElement() {
      return totalElement_;
    }
    /**
     * <code>int64 totalElement = 4;</code>
     * @param value The totalElement to set.
     * @return This builder for chaining.
     */
    public Builder setTotalElement(long value) {
      
      totalElement_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalElement = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalElement() {
      
      totalElement_ = 0L;
      onChanged();
      return this;
    }

    private long totalPage_ ;
    /**
     * <code>int64 totalPage = 5;</code>
     * @return The totalPage.
     */
    @java.lang.Override
    public long getTotalPage() {
      return totalPage_;
    }
    /**
     * <code>int64 totalPage = 5;</code>
     * @param value The totalPage to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPage(long value) {
      
      totalPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalPage = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPage() {
      
      totalPage_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.GetMovieShowtimesResponse)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.GetMovieShowtimesResponse)
  private static final com.microservice.booking_proto.GetMovieShowtimesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microservice.booking_proto.GetMovieShowtimesResponse();
  }

  public static com.microservice.booking_proto.GetMovieShowtimesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMovieShowtimesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetMovieShowtimesResponse>() {
    @java.lang.Override
    public GetMovieShowtimesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetMovieShowtimesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetMovieShowtimesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microservice.booking_proto.GetMovieShowtimesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

