// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.microservice.booking_proto;

public interface GetShowtimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.GetShowtimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.net.devh.boot.grpc.example.Showtime showtime = 3;</code>
   * @return Whether the showtime field is set.
   */
  boolean hasShowtime();
  /**
   * <code>.net.devh.boot.grpc.example.Showtime showtime = 3;</code>
   * @return The showtime.
   */
  com.microservice.booking_proto.Showtime getShowtime();
  /**
   * <code>.net.devh.boot.grpc.example.Showtime showtime = 3;</code>
   */
  com.microservice.booking_proto.ShowtimeOrBuilder getShowtimeOrBuilder();
}
