// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.microservice.booking_proto;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.UpdateShowtimeRequest}
 */
public final class UpdateShowtimeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.UpdateShowtimeRequest)
    UpdateShowtimeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateShowtimeRequest.newBuilder() to construct.
  private UpdateShowtimeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateShowtimeRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateShowtimeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_UpdateShowtimeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_UpdateShowtimeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microservice.booking_proto.UpdateShowtimeRequest.class, com.microservice.booking_proto.UpdateShowtimeRequest.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int ROOMID_FIELD_NUMBER = 2;
  private com.google.protobuf.Int32Value roomId_;
  /**
   * <code>.google.protobuf.Int32Value roomId = 2;</code>
   * @return Whether the roomId field is set.
   */
  @java.lang.Override
  public boolean hasRoomId() {
    return roomId_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value roomId = 2;</code>
   * @return The roomId.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getRoomId() {
    return roomId_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : roomId_;
  }
  /**
   * <code>.google.protobuf.Int32Value roomId = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getRoomIdOrBuilder() {
    return getRoomId();
  }

  public static final int MOVIEID_FIELD_NUMBER = 3;
  private com.google.protobuf.Int32Value movieId_;
  /**
   * <code>.google.protobuf.Int32Value movieId = 3;</code>
   * @return Whether the movieId field is set.
   */
  @java.lang.Override
  public boolean hasMovieId() {
    return movieId_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value movieId = 3;</code>
   * @return The movieId.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getMovieId() {
    return movieId_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : movieId_;
  }
  /**
   * <code>.google.protobuf.Int32Value movieId = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getMovieIdOrBuilder() {
    return getMovieId();
  }

  public static final int STARTTIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Int64Value startTime_;
  /**
   * <code>.google.protobuf.Int64Value startTime = 4;</code>
   * @return Whether the startTime field is set.
   */
  @java.lang.Override
  public boolean hasStartTime() {
    return startTime_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value startTime = 4;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getStartTime() {
    return startTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : startTime_;
  }
  /**
   * <code>.google.protobuf.Int64Value startTime = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getStartTimeOrBuilder() {
    return getStartTime();
  }

  public static final int ENDTIME_FIELD_NUMBER = 5;
  private com.google.protobuf.Int64Value endTime_;
  /**
   * <code>.google.protobuf.Int64Value endTime = 5;</code>
   * @return Whether the endTime field is set.
   */
  @java.lang.Override
  public boolean hasEndTime() {
    return endTime_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value endTime = 5;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getEndTime() {
    return endTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : endTime_;
  }
  /**
   * <code>.google.protobuf.Int64Value endTime = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getEndTimeOrBuilder() {
    return getEndTime();
  }

  public static final int DATE_FIELD_NUMBER = 6;
  private com.google.protobuf.Int64Value date_;
  /**
   * <code>.google.protobuf.Int64Value date = 6;</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value date = 6;</code>
   * @return The date.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getDate() {
    return date_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : date_;
  }
  /**
   * <code>.google.protobuf.Int64Value date = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getDateOrBuilder() {
    return getDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (roomId_ != null) {
      output.writeMessage(2, getRoomId());
    }
    if (movieId_ != null) {
      output.writeMessage(3, getMovieId());
    }
    if (startTime_ != null) {
      output.writeMessage(4, getStartTime());
    }
    if (endTime_ != null) {
      output.writeMessage(5, getEndTime());
    }
    if (date_ != null) {
      output.writeMessage(6, getDate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (roomId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRoomId());
    }
    if (movieId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMovieId());
    }
    if (startTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getStartTime());
    }
    if (endTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getEndTime());
    }
    if (date_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microservice.booking_proto.UpdateShowtimeRequest)) {
      return super.equals(obj);
    }
    com.microservice.booking_proto.UpdateShowtimeRequest other = (com.microservice.booking_proto.UpdateShowtimeRequest) obj;

    if (getId()
        != other.getId()) return false;
    if (hasRoomId() != other.hasRoomId()) return false;
    if (hasRoomId()) {
      if (!getRoomId()
          .equals(other.getRoomId())) return false;
    }
    if (hasMovieId() != other.hasMovieId()) return false;
    if (hasMovieId()) {
      if (!getMovieId()
          .equals(other.getMovieId())) return false;
    }
    if (hasStartTime() != other.hasStartTime()) return false;
    if (hasStartTime()) {
      if (!getStartTime()
          .equals(other.getStartTime())) return false;
    }
    if (hasEndTime() != other.hasEndTime()) return false;
    if (hasEndTime()) {
      if (!getEndTime()
          .equals(other.getEndTime())) return false;
    }
    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasRoomId()) {
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId().hashCode();
    }
    if (hasMovieId()) {
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + getMovieId().hashCode();
    }
    if (hasStartTime()) {
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
    }
    if (hasEndTime()) {
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
    }
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.booking_proto.UpdateShowtimeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microservice.booking_proto.UpdateShowtimeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.UpdateShowtimeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.UpdateShowtimeRequest)
      com.microservice.booking_proto.UpdateShowtimeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_UpdateShowtimeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_UpdateShowtimeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.booking_proto.UpdateShowtimeRequest.class, com.microservice.booking_proto.UpdateShowtimeRequest.Builder.class);
    }

    // Construct using com.microservice.booking_proto.UpdateShowtimeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      if (roomIdBuilder_ == null) {
        roomId_ = null;
      } else {
        roomId_ = null;
        roomIdBuilder_ = null;
      }
      if (movieIdBuilder_ == null) {
        movieId_ = null;
      } else {
        movieId_ = null;
        movieIdBuilder_ = null;
      }
      if (startTimeBuilder_ == null) {
        startTime_ = null;
      } else {
        startTime_ = null;
        startTimeBuilder_ = null;
      }
      if (endTimeBuilder_ == null) {
        endTime_ = null;
      } else {
        endTime_ = null;
        endTimeBuilder_ = null;
      }
      if (dateBuilder_ == null) {
        date_ = null;
      } else {
        date_ = null;
        dateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microservice.booking_proto.BookingProto.internal_static_net_devh_boot_grpc_example_UpdateShowtimeRequest_descriptor;
    }

    @java.lang.Override
    public com.microservice.booking_proto.UpdateShowtimeRequest getDefaultInstanceForType() {
      return com.microservice.booking_proto.UpdateShowtimeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.microservice.booking_proto.UpdateShowtimeRequest build() {
      com.microservice.booking_proto.UpdateShowtimeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microservice.booking_proto.UpdateShowtimeRequest buildPartial() {
      com.microservice.booking_proto.UpdateShowtimeRequest result = new com.microservice.booking_proto.UpdateShowtimeRequest(this);
      result.id_ = id_;
      if (roomIdBuilder_ == null) {
        result.roomId_ = roomId_;
      } else {
        result.roomId_ = roomIdBuilder_.build();
      }
      if (movieIdBuilder_ == null) {
        result.movieId_ = movieId_;
      } else {
        result.movieId_ = movieIdBuilder_.build();
      }
      if (startTimeBuilder_ == null) {
        result.startTime_ = startTime_;
      } else {
        result.startTime_ = startTimeBuilder_.build();
      }
      if (endTimeBuilder_ == null) {
        result.endTime_ = endTime_;
      } else {
        result.endTime_ = endTimeBuilder_.build();
      }
      if (dateBuilder_ == null) {
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microservice.booking_proto.UpdateShowtimeRequest) {
        return mergeFrom((com.microservice.booking_proto.UpdateShowtimeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microservice.booking_proto.UpdateShowtimeRequest other) {
      if (other == com.microservice.booking_proto.UpdateShowtimeRequest.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasRoomId()) {
        mergeRoomId(other.getRoomId());
      }
      if (other.hasMovieId()) {
        mergeMovieId(other.getMovieId());
      }
      if (other.hasStartTime()) {
        mergeStartTime(other.getStartTime());
      }
      if (other.hasEndTime()) {
        mergeEndTime(other.getEndTime());
      }
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();

              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getRoomIdFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMovieIdFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getStartTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getEndTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getDateFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int32Value roomId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> roomIdBuilder_;
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     * @return Whether the roomId field is set.
     */
    public boolean hasRoomId() {
      return roomIdBuilder_ != null || roomId_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     * @return The roomId.
     */
    public com.google.protobuf.Int32Value getRoomId() {
      if (roomIdBuilder_ == null) {
        return roomId_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : roomId_;
      } else {
        return roomIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     */
    public Builder setRoomId(com.google.protobuf.Int32Value value) {
      if (roomIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        roomId_ = value;
        onChanged();
      } else {
        roomIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     */
    public Builder setRoomId(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (roomIdBuilder_ == null) {
        roomId_ = builderForValue.build();
        onChanged();
      } else {
        roomIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     */
    public Builder mergeRoomId(com.google.protobuf.Int32Value value) {
      if (roomIdBuilder_ == null) {
        if (roomId_ != null) {
          roomId_ =
            com.google.protobuf.Int32Value.newBuilder(roomId_).mergeFrom(value).buildPartial();
        } else {
          roomId_ = value;
        }
        onChanged();
      } else {
        roomIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     */
    public Builder clearRoomId() {
      if (roomIdBuilder_ == null) {
        roomId_ = null;
        onChanged();
      } else {
        roomId_ = null;
        roomIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     */
    public com.google.protobuf.Int32Value.Builder getRoomIdBuilder() {
      
      onChanged();
      return getRoomIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getRoomIdOrBuilder() {
      if (roomIdBuilder_ != null) {
        return roomIdBuilder_.getMessageOrBuilder();
      } else {
        return roomId_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : roomId_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value roomId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getRoomIdFieldBuilder() {
      if (roomIdBuilder_ == null) {
        roomIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getRoomId(),
                getParentForChildren(),
                isClean());
        roomId_ = null;
      }
      return roomIdBuilder_;
    }

    private com.google.protobuf.Int32Value movieId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> movieIdBuilder_;
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     * @return Whether the movieId field is set.
     */
    public boolean hasMovieId() {
      return movieIdBuilder_ != null || movieId_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     * @return The movieId.
     */
    public com.google.protobuf.Int32Value getMovieId() {
      if (movieIdBuilder_ == null) {
        return movieId_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : movieId_;
      } else {
        return movieIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     */
    public Builder setMovieId(com.google.protobuf.Int32Value value) {
      if (movieIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        movieId_ = value;
        onChanged();
      } else {
        movieIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     */
    public Builder setMovieId(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (movieIdBuilder_ == null) {
        movieId_ = builderForValue.build();
        onChanged();
      } else {
        movieIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     */
    public Builder mergeMovieId(com.google.protobuf.Int32Value value) {
      if (movieIdBuilder_ == null) {
        if (movieId_ != null) {
          movieId_ =
            com.google.protobuf.Int32Value.newBuilder(movieId_).mergeFrom(value).buildPartial();
        } else {
          movieId_ = value;
        }
        onChanged();
      } else {
        movieIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     */
    public Builder clearMovieId() {
      if (movieIdBuilder_ == null) {
        movieId_ = null;
        onChanged();
      } else {
        movieId_ = null;
        movieIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     */
    public com.google.protobuf.Int32Value.Builder getMovieIdBuilder() {
      
      onChanged();
      return getMovieIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getMovieIdOrBuilder() {
      if (movieIdBuilder_ != null) {
        return movieIdBuilder_.getMessageOrBuilder();
      } else {
        return movieId_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : movieId_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value movieId = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getMovieIdFieldBuilder() {
      if (movieIdBuilder_ == null) {
        movieIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getMovieId(),
                getParentForChildren(),
                isClean());
        movieId_ = null;
      }
      return movieIdBuilder_;
    }

    private com.google.protobuf.Int64Value startTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> startTimeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     * @return Whether the startTime field is set.
     */
    public boolean hasStartTime() {
      return startTimeBuilder_ != null || startTime_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     * @return The startTime.
     */
    public com.google.protobuf.Int64Value getStartTime() {
      if (startTimeBuilder_ == null) {
        return startTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : startTime_;
      } else {
        return startTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     */
    public Builder setStartTime(com.google.protobuf.Int64Value value) {
      if (startTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startTime_ = value;
        onChanged();
      } else {
        startTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     */
    public Builder setStartTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (startTimeBuilder_ == null) {
        startTime_ = builderForValue.build();
        onChanged();
      } else {
        startTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     */
    public Builder mergeStartTime(com.google.protobuf.Int64Value value) {
      if (startTimeBuilder_ == null) {
        if (startTime_ != null) {
          startTime_ =
            com.google.protobuf.Int64Value.newBuilder(startTime_).mergeFrom(value).buildPartial();
        } else {
          startTime_ = value;
        }
        onChanged();
      } else {
        startTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     */
    public Builder clearStartTime() {
      if (startTimeBuilder_ == null) {
        startTime_ = null;
        onChanged();
      } else {
        startTime_ = null;
        startTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     */
    public com.google.protobuf.Int64Value.Builder getStartTimeBuilder() {
      
      onChanged();
      return getStartTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getStartTimeOrBuilder() {
      if (startTimeBuilder_ != null) {
        return startTimeBuilder_.getMessageOrBuilder();
      } else {
        return startTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : startTime_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getStartTimeFieldBuilder() {
      if (startTimeBuilder_ == null) {
        startTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getStartTime(),
                getParentForChildren(),
                isClean());
        startTime_ = null;
      }
      return startTimeBuilder_;
    }

    private com.google.protobuf.Int64Value endTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> endTimeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     * @return Whether the endTime field is set.
     */
    public boolean hasEndTime() {
      return endTimeBuilder_ != null || endTime_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     * @return The endTime.
     */
    public com.google.protobuf.Int64Value getEndTime() {
      if (endTimeBuilder_ == null) {
        return endTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : endTime_;
      } else {
        return endTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     */
    public Builder setEndTime(com.google.protobuf.Int64Value value) {
      if (endTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endTime_ = value;
        onChanged();
      } else {
        endTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     */
    public Builder setEndTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (endTimeBuilder_ == null) {
        endTime_ = builderForValue.build();
        onChanged();
      } else {
        endTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     */
    public Builder mergeEndTime(com.google.protobuf.Int64Value value) {
      if (endTimeBuilder_ == null) {
        if (endTime_ != null) {
          endTime_ =
            com.google.protobuf.Int64Value.newBuilder(endTime_).mergeFrom(value).buildPartial();
        } else {
          endTime_ = value;
        }
        onChanged();
      } else {
        endTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     */
    public Builder clearEndTime() {
      if (endTimeBuilder_ == null) {
        endTime_ = null;
        onChanged();
      } else {
        endTime_ = null;
        endTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     */
    public com.google.protobuf.Int64Value.Builder getEndTimeBuilder() {
      
      onChanged();
      return getEndTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getEndTimeOrBuilder() {
      if (endTimeBuilder_ != null) {
        return endTimeBuilder_.getMessageOrBuilder();
      } else {
        return endTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : endTime_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value endTime = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getEndTimeFieldBuilder() {
      if (endTimeBuilder_ == null) {
        endTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getEndTime(),
                getParentForChildren(),
                isClean());
        endTime_ = null;
      }
      return endTimeBuilder_;
    }

    private com.google.protobuf.Int64Value date_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> dateBuilder_;
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return dateBuilder_ != null || date_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     * @return The date.
     */
    public com.google.protobuf.Int64Value getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     */
    public Builder setDate(com.google.protobuf.Int64Value value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     */
    public Builder setDate(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     */
    public Builder mergeDate(com.google.protobuf.Int64Value value) {
      if (dateBuilder_ == null) {
        if (date_ != null) {
          date_ =
            com.google.protobuf.Int64Value.newBuilder(date_).mergeFrom(value).buildPartial();
        } else {
          date_ = value;
        }
        onChanged();
      } else {
        dateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = null;
        onChanged();
      } else {
        date_ = null;
        dateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     */
    public com.google.protobuf.Int64Value.Builder getDateBuilder() {
      
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value date = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.UpdateShowtimeRequest)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.UpdateShowtimeRequest)
  private static final com.microservice.booking_proto.UpdateShowtimeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microservice.booking_proto.UpdateShowtimeRequest();
  }

  public static com.microservice.booking_proto.UpdateShowtimeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateShowtimeRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateShowtimeRequest>() {
    @java.lang.Override
    public UpdateShowtimeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateShowtimeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateShowtimeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microservice.booking_proto.UpdateShowtimeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

