// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.microservice.auth_proto;

public final class AuthProto {
  private AuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_AuthenticateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_AuthenticateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_AuthenticateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_AuthenticateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_IdentityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_IdentityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_IdentityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_IdentityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\032net.devh.boot.grpc.example" +
      "\"$\n\023AuthenticateRequest\022\r\n\005token\030\001 \001(\t\"D" +
      "\n\024AuthenticateResponse\022\017\n\007isValid\030\001 \001(\010\022" +
      "\016\n\006userId\030\002 \001(\t\022\013\n\003ttl\030\003 \001(\003\"!\n\017Identity" +
      "Request\022\016\n\006userId\030\001 \001(\005\"1\n\020IdentityRespo" +
      "nse\022\016\n\006active\030\001 \001(\010\022\r\n\005roles\030\002 \001(\t2\353\001\n\013A" +
      "uthService\022s\n\016doAuthenticate\022/.net.devh." +
      "boot.grpc.example.AuthenticateRequest\0320." +
      "net.devh.boot.grpc.example.AuthenticateR" +
      "esponse\022g\n\ndoIdentity\022+.net.devh.boot.gr" +
      "pc.example.IdentityRequest\032,.net.devh.bo" +
      "ot.grpc.example.IdentityResponseB*\n\033com." +
      "microservice.auth_protoB\tAuthProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_devh_boot_grpc_example_AuthenticateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_devh_boot_grpc_example_AuthenticateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_AuthenticateRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_net_devh_boot_grpc_example_AuthenticateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_devh_boot_grpc_example_AuthenticateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_AuthenticateResponse_descriptor,
        new java.lang.String[] { "IsValid", "UserId", "Ttl", });
    internal_static_net_devh_boot_grpc_example_IdentityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_devh_boot_grpc_example_IdentityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_IdentityRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_net_devh_boot_grpc_example_IdentityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_net_devh_boot_grpc_example_IdentityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_IdentityResponse_descriptor,
        new java.lang.String[] { "Active", "Roles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
