// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.microservice.movie_proto;

public interface GetNowPlayingMoviesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.GetNowPlayingMoviesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>string sort = 3;</code>
   * @return The sort.
   */
  java.lang.String getSort();
  /**
   * <code>string sort = 3;</code>
   * @return The bytes for sort.
   */
  com.google.protobuf.ByteString
      getSortBytes();
}
