// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.microservice.movie_proto;

public interface GetNowPlayingMoviesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.GetNowPlayingMoviesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .net.devh.boot.grpc.example.Movie movies = 3;</code>
   */
  java.util.List<com.microservice.movie_proto.Movie> 
      getMoviesList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.Movie movies = 3;</code>
   */
  com.microservice.movie_proto.Movie getMovies(int index);
  /**
   * <code>repeated .net.devh.boot.grpc.example.Movie movies = 3;</code>
   */
  int getMoviesCount();
  /**
   * <code>repeated .net.devh.boot.grpc.example.Movie movies = 3;</code>
   */
  java.util.List<? extends com.microservice.movie_proto.MovieOrBuilder> 
      getMoviesOrBuilderList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.Movie movies = 3;</code>
   */
  com.microservice.movie_proto.MovieOrBuilder getMoviesOrBuilder(
      int index);

  /**
   * <code>int64 totalPage = 4;</code>
   * @return The totalPage.
   */
  long getTotalPage();

  /**
   * <code>int64 totalElement = 5;</code>
   * @return The totalElement.
   */
  long getTotalElement();
}
