// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

package com.microservice.websocket_proto;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.CreatePreSeatReservationRequest}
 */
public final class CreatePreSeatReservationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.CreatePreSeatReservationRequest)
    CreatePreSeatReservationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreatePreSeatReservationRequest.newBuilder() to construct.
  private CreatePreSeatReservationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreatePreSeatReservationRequest() {
    seats_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreatePreSeatReservationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microservice.websocket_proto.WebSocketProto.internal_static_net_devh_boot_grpc_example_CreatePreSeatReservationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microservice.websocket_proto.WebSocketProto.internal_static_net_devh_boot_grpc_example_CreatePreSeatReservationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microservice.websocket_proto.CreatePreSeatReservationRequest.class, com.microservice.websocket_proto.CreatePreSeatReservationRequest.Builder.class);
  }

  public static final int SHOWTIMEID_FIELD_NUMBER = 1;
  private int showtimeId_;
  /**
   * <code>int32 showtimeId = 1;</code>
   * @return The showtimeId.
   */
  @java.lang.Override
  public int getShowtimeId() {
    return showtimeId_;
  }

  public static final int SEATS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.IntList seats_;
  /**
   * <code>repeated int32 seats = 2;</code>
   * @return A list containing the seats.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getSeatsList() {
    return seats_;
  }
  /**
   * <code>repeated int32 seats = 2;</code>
   * @return The count of seats.
   */
  public int getSeatsCount() {
    return seats_.size();
  }
  /**
   * <code>repeated int32 seats = 2;</code>
   * @param index The index of the element to return.
   * @return The seats at the given index.
   */
  public int getSeats(int index) {
    return seats_.getInt(index);
  }
  private int seatsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (showtimeId_ != 0) {
      output.writeInt32(1, showtimeId_);
    }
    if (getSeatsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(seatsMemoizedSerializedSize);
    }
    for (int i = 0; i < seats_.size(); i++) {
      output.writeInt32NoTag(seats_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (showtimeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, showtimeId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < seats_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(seats_.getInt(i));
      }
      size += dataSize;
      if (!getSeatsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      seatsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microservice.websocket_proto.CreatePreSeatReservationRequest)) {
      return super.equals(obj);
    }
    com.microservice.websocket_proto.CreatePreSeatReservationRequest other = (com.microservice.websocket_proto.CreatePreSeatReservationRequest) obj;

    if (getShowtimeId()
        != other.getShowtimeId()) return false;
    if (!getSeatsList()
        .equals(other.getSeatsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SHOWTIMEID_FIELD_NUMBER;
    hash = (53 * hash) + getShowtimeId();
    if (getSeatsCount() > 0) {
      hash = (37 * hash) + SEATS_FIELD_NUMBER;
      hash = (53 * hash) + getSeatsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microservice.websocket_proto.CreatePreSeatReservationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.CreatePreSeatReservationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.CreatePreSeatReservationRequest)
      com.microservice.websocket_proto.CreatePreSeatReservationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservice.websocket_proto.WebSocketProto.internal_static_net_devh_boot_grpc_example_CreatePreSeatReservationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservice.websocket_proto.WebSocketProto.internal_static_net_devh_boot_grpc_example_CreatePreSeatReservationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservice.websocket_proto.CreatePreSeatReservationRequest.class, com.microservice.websocket_proto.CreatePreSeatReservationRequest.Builder.class);
    }

    // Construct using com.microservice.websocket_proto.CreatePreSeatReservationRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      showtimeId_ = 0;

      seats_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microservice.websocket_proto.WebSocketProto.internal_static_net_devh_boot_grpc_example_CreatePreSeatReservationRequest_descriptor;
    }

    @java.lang.Override
    public com.microservice.websocket_proto.CreatePreSeatReservationRequest getDefaultInstanceForType() {
      return com.microservice.websocket_proto.CreatePreSeatReservationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.microservice.websocket_proto.CreatePreSeatReservationRequest build() {
      com.microservice.websocket_proto.CreatePreSeatReservationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microservice.websocket_proto.CreatePreSeatReservationRequest buildPartial() {
      com.microservice.websocket_proto.CreatePreSeatReservationRequest result = new com.microservice.websocket_proto.CreatePreSeatReservationRequest(this);
      int from_bitField0_ = bitField0_;
      result.showtimeId_ = showtimeId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        seats_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.seats_ = seats_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microservice.websocket_proto.CreatePreSeatReservationRequest) {
        return mergeFrom((com.microservice.websocket_proto.CreatePreSeatReservationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microservice.websocket_proto.CreatePreSeatReservationRequest other) {
      if (other == com.microservice.websocket_proto.CreatePreSeatReservationRequest.getDefaultInstance()) return this;
      if (other.getShowtimeId() != 0) {
        setShowtimeId(other.getShowtimeId());
      }
      if (!other.seats_.isEmpty()) {
        if (seats_.isEmpty()) {
          seats_ = other.seats_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSeatsIsMutable();
          seats_.addAll(other.seats_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              showtimeId_ = input.readInt32();

              break;
            } // case 8
            case 16: {
              int v = input.readInt32();
              ensureSeatsIsMutable();
              seats_.addInt(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureSeatsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                seats_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int showtimeId_ ;
    /**
     * <code>int32 showtimeId = 1;</code>
     * @return The showtimeId.
     */
    @java.lang.Override
    public int getShowtimeId() {
      return showtimeId_;
    }
    /**
     * <code>int32 showtimeId = 1;</code>
     * @param value The showtimeId to set.
     * @return This builder for chaining.
     */
    public Builder setShowtimeId(int value) {
      
      showtimeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 showtimeId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowtimeId() {
      
      showtimeId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList seats_ = emptyIntList();
    private void ensureSeatsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        seats_ = mutableCopy(seats_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 seats = 2;</code>
     * @return A list containing the seats.
     */
    public java.util.List<java.lang.Integer>
        getSeatsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(seats_) : seats_;
    }
    /**
     * <code>repeated int32 seats = 2;</code>
     * @return The count of seats.
     */
    public int getSeatsCount() {
      return seats_.size();
    }
    /**
     * <code>repeated int32 seats = 2;</code>
     * @param index The index of the element to return.
     * @return The seats at the given index.
     */
    public int getSeats(int index) {
      return seats_.getInt(index);
    }
    /**
     * <code>repeated int32 seats = 2;</code>
     * @param index The index to set the value at.
     * @param value The seats to set.
     * @return This builder for chaining.
     */
    public Builder setSeats(
        int index, int value) {
      ensureSeatsIsMutable();
      seats_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 seats = 2;</code>
     * @param value The seats to add.
     * @return This builder for chaining.
     */
    public Builder addSeats(int value) {
      ensureSeatsIsMutable();
      seats_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 seats = 2;</code>
     * @param values The seats to add.
     * @return This builder for chaining.
     */
    public Builder addAllSeats(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureSeatsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, seats_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 seats = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeats() {
      seats_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.CreatePreSeatReservationRequest)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.CreatePreSeatReservationRequest)
  private static final com.microservice.websocket_proto.CreatePreSeatReservationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microservice.websocket_proto.CreatePreSeatReservationRequest();
  }

  public static com.microservice.websocket_proto.CreatePreSeatReservationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatePreSeatReservationRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreatePreSeatReservationRequest>() {
    @java.lang.Override
    public CreatePreSeatReservationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreatePreSeatReservationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreatePreSeatReservationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microservice.websocket_proto.CreatePreSeatReservationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

