name: Build and deploy Spring application to DigitalOcean Droplet.

on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_KEYS }}
          port: 22
          script: |
            echo "Deploying Spring application to DigitalOcean Droplet."
            echo "Pulling and Packaging Spring application."
            cd ./movie-reservation-microservice
            git pull origin main
            mvn clean
            mvn compile
            mvn package

            echo "Containerizing Spring application."
            docker build -t service-discovery:1.0 ./app/service-discovery/
            docker build -t api-gateway:1.0 ./app/api-gateway/
            docker build -t bff:1.0 ./app/bff/
            docker build -t auth-service:1.0 ./app/auth-service/
            docker build -t movie-service:1.0 ./app/movie-service/
            docker build -t booking-service:1.0 ./app/booking-service/

            echo "Deploying Spring application to DigitalOcean Droplet."
            docker-compose up -d
            echo  "Spring application deployed successfully."