name: Build and deploy Spring application to DigitalOcean Droplet.

on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: MaivMinh
          password: ${{ secrets.ACCESS_TOKEN_DROPLET }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_KEYS }}
          port: 22
          script: |
            echo "Deploying Spring application to DigitalOcean Droplet."
            echo "Stopping and removing existing containers."
            cd ./movie-reservation-microservice
            docker compose down || { echo "Failed to stop and remove containers"; exit 1; }
            
            echo "Pulling and Packaging Spring application."
            git pull origin main
            mvn clean
            mvn compile
            mvn package
            
            docker build -t service-discovery:1.0 ./app/service-discovery/ || { echo "Failed to build service-discovery"; exit 1; }
            docker build -t api-gateway:1.0 ./app/api-gateway/ || { echo "Failed to build api-gateway"; exit 1; }
            docker build -t bff:1.0 ./app/bff/ || { echo "Failed to build bff"; exit 1; }
            docker build -t auth-service:1.0 ./app/auth-service/ || { echo "Failed to build auth-service"; exit 1; }
            docker build -t movie-service:1.0 ./app/movie-service/ || { echo "Failed to build movie-service"; exit 1; }
            docker build -t booking-service:1.0 ./app/booking-service/ || { echo "Failed to build booking-service"; exit 1; }
            docker build -t websocket-service:1.0 ./app/websocket-service/ || { echo "Failed to build websocket-service"; exit 1; }
            
            echo "Deploying Spring application to DigitalOcean Droplet."
            docker compose up -d || { echo "Failed to start containers"; exit 1; }
            echo "Spring application deployed successfully."
